;; Exercise 1.9
;; Each of the following two procedures defines a method for adding two positive
;; integers in terms of the procedures inc, which increments its argument by 1,
;; and dec, which decrements its argument by 1.
;; Using the substitution model, illustrate the process generated by each
;; procedure in evaluating (+ 4 5).
;; Are these processes iterative or recursive?

(ns sicp-mailonline.exercises.1-9-test
  (:require [clojure.test :refer :all]))

(defn- addr [a b]
  (if (= a 0)
    b
    (inc (addr (dec a) b))))

;; (addr 4 5)
;; (inc (addr 3 5))
;; (inc (inc (addr 2 5)))
;; (inc (inc (inc (addr 1 5))))
;; (inc (inc (inc (inc (addr 0 5)))))
;; (inc (inc (inc (inc 5))))
;; (inc (inc (inc 6)))
;; (inc (inc 7))
;; (inc 8)
;; => 9
;; recursive process

(defn- addi [a b]
  (if (= a 0)
    b
    (addi (dec a) (inc b))))

;; (addi 4 5)
;; (addi 3 6)
;; (addi 2 7)
;; (addi 1 8)
;; (addi 0 9)
;; => 9
;; iterative process

(deftest exercise1-9
  (testing "add via recursive process"
    (let [+ addr]
      (is (= 9
             (+ 4 5)))))

  (testing "add via iterative process"
    (let [+ addi]
      (is (= 9
             (+ 4 5))))))
