;; Exercise 3.11
;; In section 3.2.3 we saw how the environment model described the behaviour of
;; procedures with local state.  Now we have seen how internal definitions
;; work.  A typical message-passing procedure contains both of these aspects.
;; Consider the bank account procedure of section 3.1.1:
;;
;; (define (make-account balance)
;;   (define (withdraw amount)
;;     (if (>= balance amount)
;;       (begin (set! balance (- balance amount))
;;              balance)
;;       "Insufficient funds"))
;;   (define (deposit amount)
;;     (set! balance (+ balance amount))
;;     balance)
;;   (define (dispatch m)
;;     (cond ((eq? m 'withdraw) withdraw)
;;           ((eq? m 'deposit) deposit)
;;           (else (error "Unknown request -- MAKE-ACCOUNT" m))))
;;   dispatch)
;;
;; Show the environment structure generated by the sequence of interactions
;;
;; (define acc (make-account 50))
;;
;; ((acc 'deposit) 40)
;; -> 90
;;
;; ((acc 'withdraw) 60)
;; -> 30
;;
;; Where is the local state for acc kept?  Suppose we define another account
;;
;; (define acc2 (make-account 100))
;;
;; How are the local states for the two accounts kept distinct?  Which parts of
;; the environment structure are shared between acc and acc2?

;; (define acc (make-account 50))
;;
;; global env |------------------------------------------|
;;            | make-account: *    acc: *                |
;;            |------------------------------------------|
;;                            | ^       |              ^
;;                            | |       |              |
;; params: balance            * *       |              |
;; body: (define (withdraw...           |              |
;;                                      |              |
;;                                      |  E1->|-------------------|
;;                                      |      | balance: 50       |
;;                                      |      | withdraw:       * |
;;                                      |      | deposit:     *  | |
;;                                      |      | dispatch: *  |  | |
;;                                      |      |-------------------|
;;                                      |                  |^ |^ |^
;;                                      |                  v| v| v|
;;                                      |----------------->** ** **

;; ((acc 'deposit) 40)
;;                                            after set!
;;                    |                                                    |
;;                    |                                                    |
;;          E1->|------------ |                                  E1->|------------ |
;;              | balance: 50 |                                      | balance: 90 |
;;              | withdraw:   |                                      | withdraw:   |
;;              | deposit:    |                                      | deposit:    |
;;              | dispatch:   |                                      | dispatch:   |
;;              |-------------|                                      |-------------|
;;                ^          ^                                         ^          ^
;;                |          |                                         |          |
;; E2->|-------------| E3->|------------|               E2->|-------------| E3->|------------|
;;     | m: 'deposit |     | amount: 40 |                   | m: 'deposit |     | amount: 40 |
;;     |-------------|     |------------|                   |-------------|     |------------|

;; ((acc 'withdraw) 60)
;;                                            after set!
;;                    |                                                    |
;;                    |                                                    |
;;          E1->|------------ |                                  E1->|------------ |
;;              | balance: 90 |                                      | balance: 30 |
;;              | withdraw:   |                                      | withdraw:   |
;;              | deposit:    |                                      | deposit:    |
;;              | dispatch:   |                                      | dispatch:   |
;;              |-------------|                                      |-------------|
;;                ^          ^                                         ^          ^
;;                |          |                                         |          |
;; E4->|-------------| E5->|------------|               E4->|-------------| E5->|------------|
;;     | m: 'withdraw|     | amount: 60 |                   | m: 'withdraw|     | amount: 60 |
;;     |-------------|     |------------|                   |-------------|     |------------|
;;
;; The local state for acc is kept in E1.

;; (define acc2 (make-account 100))
;;
;; global env |------------------------------------------------------------------------------------|
;;            | make-account: *    acc: *                        acc2: *                           |
;;            |------------------------------------------------------------------------------------|
;;                            | ^       |              ^               |               ^
;;                            | |       |              |               |               |
;; params: balance            * *       |              |               |               |
;; body: (define (withdraw...           |              |               |               |
;;                                      |              |               |               |
;;                                      |  E1->|-------------------|   |  E6->|-------------------|
;;                                      |      | balance: 30       |   |      | balance: 100      |
;;                                      |      | withdraw:       * |   |      | withdraw:       * |
;;                                      |      | deposit:     *  | |   |      | deposit:     *  | |
;;                                      |      | dispatch: *  |  | |   |      | dispatch: *  |  | |
;;                                      |      |-------------------|   |      |-------------------|
;;                                      |                  |^ |^ |^    |                  |^ |^ |^
;;                                      |                  v| v| v|    |                  v| v| v|
;;                                      |----------------->** ** **    |----------------->** ** **
;;
;; Each account has its own environment in which local state is stored.
;; The only sharing in this example, is that both environments share the global
;; environment as their parent, in which make-account is defined.
